sequenceDiagram
    participant Client
    participant eulabia_director
    Client->>eulabia_director: create_target
    eulabia_director->>Client: created_target [target_id]
    Client->>eulabia_director: modify_target/hosts [target_id, actual_hosts]
    eulabia_director->>Client: modified_target/hosts [target_id]
    Client->>eulabia_director: modify_target/ports [target_id, actual_ports]
    eulabia_director->>Client: modified_target/ports [target_id]
    Client->>eulabia_director: modify_target/plugins [target_id, plugins[oid/family/group]]
    eulabia_director->>Client: modified_target/plugins [target_id]
    Client->>eulabia_director: modify_target/scanner [target_id, scanner]
    eulabia_director->>Client: modified_target/scanner [target_id]
    Note right of Client: Optional Settings
    Client->>eulabia_director: modify_target/exlude_hosts [target_id, actual_exlude_hosts]
    eulabia_director->>Client: modified_target/exlude_hosts [target_id]
    Client->>eulabia_director: modify_target/only_alive_hosts [target_id, only_alive_hosts]
    eulabia_director->>Client: modified_target/only_alive_hosts [target_id]
    Client->>eulabia_director: modify_target/scan_host_parallel [target_id, scan_host_parallel]
    eulabia_director->>Client: modified_target/scan_host_parallel [target_id]
    Note right of Client: TBD: Credentials for the scan 
    Client->>eulabia_director: create_target/credential [target_id]
    eulabia_director->>Client: created_target/credential [target_id, credential_id]