sequenceDiagram
    participant client
    participant eulabeia_director
    participant eulabeia_sensor
    participant scanner
    
    client->>eulabeia_director: start_scan [scan_id]
    Note right of eulabeia_director: Based on target information the scanner is chosen<br>loop Until sensor has sufficient memory

    eulabeia_director->>eulabeia_sensor: start_scan  [scan_id]
    Note right of eulabeia_sensor: A sensor needs to check if it has sufficient memory to start the scan<br> When it does have sufficient memory then it should ask for scan details.
    eulabeia_sensor->>eulabeia_director: get_scan [scan_id]
    eulabeia_director->>eulabeia_sensor: got_scan [scan_id, target]
    eulabeia_sensor->>+scanner: start_scanner [target]
    
    eulabeia_sensor->>eulabeia_director: started_scan [scan_id]
    eulabeia_sensor->>client: started_scan [scan_id]
    loop Results
        scanner->>eulabeia_sensor: got_result [scan_id, oid, key, value]
        scanner->>eulabeia_director: got_result [scan_id, oid, key, value]
        eulabeia_director->>client: got_percentage [scan_id, percentage]
        scanner->>client: got_result [scan_id, oid, key value]
    end
    scanner->>-eulabeia_sensor: stopped_scan [scan_id, status]
    eulabeia_sensor->>eulabeia_director: stopped_scan [scan_id, status]
    eulabeia_sensor->>client: stopped_scan [scan_id, status]
