Context = "scanner"
title = "eulabeia config"

[Connection]
server = "0.0.0.0:1883"
timeout = 10 # in seconds

[ScannerPreferences]
scanInfoStoreTime = 0 # in hours
maxScan = 0  # 0 = disabled
minFreeMemScanQueue = 0  # 0 = disabled
maxQueuedScans = 0  # 0 = disabled
niceness = 10

[Sensor]
ID = "hiddenhorst"
Tunnel = true

[Feedservice]
RedisDbAddress = "/run/redis/redis.sock"

[Preferences]
config = "~/.eulabeia/config.toml"
logFile = ""
logLevel = ""
