sequenceDiagram
    participant Client
    participant eulabeia_director
    Client->>eulabeia_director: create_target
    eulabeia_director->>Client: created_target [target_id]
    Client->>eulabeia_director: modify_target/hosts [target_id, actual_hosts]
    eulabeia_director->>Client: modified_target/hosts [target_id]
    Client->>eulabeia_director: modify_target/ports [target_id, actual_ports]
    eulabeia_director->>Client: modified_target/ports [target_id]
    Client->>eulabeia_director: modify_target/plugins [target_id, plugins[oid/family/group]]
    eulabeia_director->>Client: modified_target/plugins [target_id]
    Client->>eulabeia_director: modify_target/scanner [target_id, scanner]
    eulabeia_director->>Client: modified_target/scanner [target_id]
    Note right of Client: Optional Settings
    Client->>eulabeia_director: modify_target/exlude_hosts [target_id, actual_exlude_hosts]
    eulabeia_director->>Client: modified_target/exlude_hosts [target_id]
    Client->>eulabeia_director: modify_target/only_alive_hosts [target_id, only_alive_hosts]
    eulabeia_director->>Client: modified_target/only_alive_hosts [target_id]
    Client->>eulabeia_director: modify_target/scan_host_parallel [target_id, scan_host_parallel]
    eulabeia_director->>Client: modified_target/scan_host_parallel [target_id]
    Note right of Client: TBD: Credentials for the scan 
    Client->>eulabeia_director: create_target/credential [target_id]
    eulabeia_director->>Client: created_target/credential [target_id, credential_id]
